exports.seed = function(knex) {
  return knex("rivers")
    .del()
    .then(function() {
      return knex("rivers").insert([
        {
          usgsId: "09010500",
          name: "COLORADO RIVER",
          geoTag: "BELOW BAKER GULCH NR GRAND LAKE, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: 9.82,
          meanCFS: 8.3,
          medianCFS: 8.1,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09015000",
          name: "COLORADO RIVER",
          geoTag: "BELOW SHADOW MOUNTAIN RESERVOIR, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: 22.3,
          meanCFS: 24,
          medianCFS: 23,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09019000",
          name: "COLORADO RIVER",
          geoTag: "BELOW LAKE GRANBY, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: 20.5,
          meanCFS: "---",
          medianCFS: "---",
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09019500",
          name: "COLORADO RIVER",
          geoTag: "NEAR GRANBY, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: 24.6,
          meanCFS: 25,
          medianCFS: 26,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09034250",
          name: "COLORADO RIVER",
          geoTag: "AT WINDY GAP, NEAR GRANBY, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: "Bkw",
          meanCFS: 79,
          medianCFS: 78,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "09058000",
          name: "COLORADO RIVER",
          geoTag: "NEAR KREMMLING, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: 426,
          meanCFS: 517,
          medianCFS: 501,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "09060799",
          name: "COLORADO RIVER",
          geoTag: "AT CATAMOUNT BRIDGE, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: 667,
          meanCFS: "---",
          medianCFS: "---",
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "09070500",
          name: "COLORADO RIVER",
          geoTag: "NEAR DOTSERO, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: "Ice",
          meanCFS: 891,
          medianCFS: 870,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09085100",
          name: "COLORADO RIVER",
          geoTag: "BELOW GLENWOOD SPRINGS, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: "1,200",
          meanCFS: "1,409",
          medianCFS: "1,370",
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09095500",
          name: "COLORADO RIVER",
          geoTag: "NEAR CAMEO, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: "1,190",
          meanCFS: "1,550",
          medianCFS: "1,500",
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "09163500",
          name: "COLORADO RIVER",
          geoTag: "NEAR COLORADO-UTAH STATE LINE",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Colorado Basin",
          currentCFS: "2,190",
          meanCFS: "3,200",
          medianCFS: "2,910",
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07079300",
          name: "East Fork Arkansas River",
          geoTag: "AT US HIGHWAY 24, NR LEADVILLE, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: "Ice",
          meanCFS: 11,
          medianCFS: 11,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07081200",
          name: "ARKANSAS RIVER",
          geoTag: "NEAR LEADVILLE, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: "Ice",
          meanCFS: 16,
          medianCFS: 16,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07083710",
          name: "ARKANSAS RIVER",
          geoTag: "BELOW EMPIRE GULCH NEAR MALTA, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 79.2,
          meanCFS: 53,
          medianCFS: 49,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07087050",
          name: "ARKANSAS RIVER",
          geoTag: "BELOW GRANITE, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 148,
          meanCFS: "---",
          medianCFS: "---",
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07091200",
          name: "ARKANSAS RIVER",
          geoTag: "NEAR NATHROP, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: "Ssn",
          meanCFS: 245,
          medianCFS: 216,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07094500",
          name: "ARKANSAS RIVER",
          geoTag: "AT PARKDALE, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 350,
          meanCFS: 395,
          medianCFS: 350,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07099970",
          name: "ARKANSAS RIVER",
          geoTag: "AT MOFFAT STREET AT PUEBLO, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 117,
          meanCFS: 97,
          medianCFS: 70,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07099973",
          name: "ARKANSAS RIVER TRIBUTARY",
          geoTag: "ABOVE HWY 227 AT PUEBLO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 1.7,
          meanCFS: 20,
          medianCFS: 27,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07109500",
          name: "ARKANSAS RIVER",
          geoTag: "NEAR AVONDALE, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 291,
          meanCFS: 354,
          medianCFS: 314,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07124000",
          name: "ARKANSAS RIVER",
          geoTag: "AT LAS ANIMAS, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 89.2,
          meanCFS: 174,
          medianCFS: 120,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07130500",
          name: "ARKANSAS RIVER",
          geoTag: "BELOW JOHN MARTIN RESERVOIR, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 0.77,
          meanCFS: 13,
          medianCFS: 2,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07133000",
          name: "ARKANSAS RIVER AT LAMAR, CO",
          geoTag: "AT LAMAR, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 15.8,
          meanCFS: 34,
          medianCFS: 22,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "07134180",
          name: "ARKANSAS RIVER",
          geoTag: "NEAR GRANADA, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 45.5,
          meanCFS: 106,
          medianCFS: 87,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "07137500",
          name: "ARKANSAS River",
          geoTag: "NR COOLIDGE, KS",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "Arkansas Basin",
          currentCFS: 60.4,
          meanCFS: 127,
          medianCFS: 118,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "06620000",
          name: "NORTH PLATTE RIVER",
          geoTag: "NEAR NORTHGATE, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: "Ice",
          meanCFS: 87,
          medianCFS: 81,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "06700000",
          name: "SOUTH PLATTE RIVER",
          geoTag: "ABOVE CHEESMAN LAKE, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 106,
          meanCFS: 12,
          medianCFS: 11,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "06701900",
          name: "SOUTH PLATTE RIVER",
          geoTag: "BLW BRUSH CRK NEAR TRUMBULL, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 95.3,
          meanCFS: 119,
          medianCFS: 116,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "06710247",
          name: "SOUTH PLATTE RIVER",
          geoTag: "BELOW UNION AVE, AT ENGLEWOOD,C",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 26.7,
          meanCFS: 41,
          medianCFS: 37,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "06711565",
          name: "SOUTH PLATTE RIVER",
          geoTag: "AT ENGLEWOOD, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 61.3,
          meanCFS: 69,
          medianCFS: 65,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: false
        },
        {
          usgsId: "06714215",
          name: "SOUTH PLATTE RIVER",
          geoTag: "AT 64TH AVE. COMMERCE CITY, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 20.7,
          meanCFS: 50,
          medianCFS: 16,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "06721000",
          name: "SOUTH PLATTE RIVER",
          geoTag: "AT FORT LUPTON, CO.",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 192,
          meanCFS: 216,
          medianCFS: 227,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        },
        {
          usgsId: "06759500",
          name: "SOUTH PLATTE RIVER AT FORT MORGAN, CO",
          geoTag: "AT FORT MORGAN, CO",
          state: "CO",
          country: "USA",
          lat: "40.0589° N",
          long: "106.3889° W",
          watershed: "South Platte Basin",
          currentCFS: 189,
          meanCFS: 495,
          medianCFS: 361,
          warmWater: false,
          lowWater: false,
          highWater: false,
          iced: true,
          defaultDisplay: true
        }
      ]);
    });
};
