exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("rivers")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("rivers").insert([
        {
          name: "Colorado River",
          geo_tag: "Kremmling",
          state: "CO",
          country: "USA",
          watershed: "Colorado River",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 1450,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Roaring Fork",
          geo_tag: "Aspen",
          state: "CO",
          country: "USA",
          watershed: "Colorado River",
          usgs_id: "1245",
          lat: "54.22",
          long: "107.93",
          current_cfs: 450,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Eagle River",
          geo_tag: "Eagle",
          state: "CO",
          country: "USA",
          watershed: "Colorado River",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 460,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Frying Pan",
          geo_tag: "Basalt",
          state: "CO",
          country: "USA",
          watershed: "Colorado River",
          usgs_id: "1247",
          lat: "55.22",
          long: "108.93",
          current_cfs: 1450,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Gore Creek",
          geo_tag: "Vail",
          state: "CO",
          country: "USA",
          watershed: "Colorado River",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 150,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "South Platte",
          geo_tag: "Deckers",
          state: "CO",
          country: "USA",
          watershed: "South Platte",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 350,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Arkansas River",
          geo_tag: "Canon City",
          state: "CO",
          country: "USA",
          watershed: "Arkansas",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 254,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Arkansas River",
          geo_tag: "Granite",
          state: "CO",
          country: "USA",
          watershed: "Arkansas",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 0,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Arkansas River",
          geo_tag: "Below Pueblo Reservoir",
          state: "CO",
          country: "USA",
          watershed: "Arkansas",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 106,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Arkansas River",
          geo_tag: "Near Wellsville",
          state: "CO",
          country: "USA",
          watershed: "Arkansas",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 270,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Arkansas River",
          geo_tag: "Salida",
          state: "CO",
          country: "USA",
          watershed: "Arkansas",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 258,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Arkansas River",
          geo_tag: "Leadville",
          state: "CO",
          country: "USA",
          watershed: "Arkansas",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 0,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Blue River",
          geo_tag: "Silverthorne",
          state: "CO",
          country: "USA",
          watershed: "Colorado",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 64,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Blue River",
          geo_tag: "Dillon",
          state: "CO",
          country: "USA",
          watershed: "Colorado",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 58,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Blue River",
          geo_tag: "Green Mountain",
          state: "CO",
          country: "USA",
          watershed: "Colorado",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 270,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        },
        {
          name: "Colorado River",
          geo_tag: "Windy Gap (Chimney Rock)",
          state: "CO",
          country: "USA",
          watershed: "Colorado",
          usgs_id: "1244",
          lat: "55.22",
          long: "108.93",
          current_cfs: 0,
          warm_water: false,
          low_flows: false,
          high_water: false,
          iced: true
        }
      ]);
    });
};
